name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_padding: 60
          plugin_lines: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_languages_ignored: html, css, sass, scss, less, shell, dockerfile
          plugin_languages_details: bytes-size, percentage
          plugin_languages_skipped: z9956/RSSHub, RSSHub
