name: Scheduled Screenshot

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  screenshot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      
        
    - name: Install dependencies
      run: npm install
      
    - name: Take and save screenshot
      run: node index.js
      
      
    - name: Upload screenshot artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: snapshot.png
