name: Scheduled Screenshot

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]

jobs:
  screenshot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      
        
    - name: Install dependencies
      run: npm install
      
    - name: Take and save screenshot
      run: node index.js
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add screenshot.png
        git commit -m "Update screenshot"
        git push
